// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aepetria_vue_api.DAL;

namespace aepetria_vue_api.Migrations
{
    [DbContext(typeof(AepetriaDbContext))]
    [Migration("20191103153349_RemoteImages")]
    partial class RemoteImages
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("aepetria_vue_api.DAL.Models.RemoteImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Filename")
                        .IsRequired();

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastModified");

                    b.HasKey("Id");

                    b.ToTable("RemoteImages");
                });
#pragma warning restore 612, 618
        }
    }
}
